### ISSUE TITLE
Deploy queue

### ISSUE THREAD

**Issue by negebauer** [negebauer/IIC2173-Arqui#41]
Queue 1 replica
Redis 1 replica

@menavarrete @ironcadiz any important stuff about the deploy pls here, like ENV vars or commands

#### TODO

- [x] Separate queue from queue UI
- [x] Deploy queue, 1 replica, worker node `/queue`
- [x] Deploy redis, 1 replica, manager node
- [x] Deploy queue UI, 1 replica, manager node `/qv`
